apiVersion: v1
kind: Service
metadata:
  name: static-svc

spec:
  type: NodePort

  selector:
    app: static

  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}